[package]
name = "crabitat-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
crabitat-core = { path = "../crabitat-core" }
serde.workspace = true
uuid.workspace = true
